#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isBalanced' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def isBalanced(s):
    S=[]
    bracket={")": "(", "}": "{", "]":"["}
    for i in s:
        if i in bracket.values():  
            S.append(i)
        elif i in bracket.keys():  
            if S and S[-1] == bracket[i]:
                S.pop()
            else:
                return "NO"  
    if not S:
        return "YES"
    else:
        return "NO"  

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
